export enum ExceptionType {
    NETWORK_ERROR = "NETWORK_ERROR",
    PARSING_ERROR = "PARSING_ERROR",
    SERVER_ERROR = "SERVER_ERROR",
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
    UNAUTHORIZE_REQUEST = "UNAUTHORIZE_REQUEST",
    FORBIDDEN_REQUEST = "FORBIDDEN_REQUEST",
    BAD_REQUEST = "BAD_REQUEST",
}
